---
- hosts: all

  vars:
    applications:
      - atom
      - caffeine
      - clipmenu
      - iterm2
      - mou
      - postgres
    application_dir: /Applications
    brews:
      - ack
      - curl
      - git
      - openssl
      - python
      - sqlite
    dotfiles_dir: ~/dotfiles
    name: YOUR_NAME_HERE
    email: YOUR_EMAIL_HERE
    github_username: YOUR_USERNAME_HERE
    zsh_path: /bin/zsh

  tasks:
    - include: tasks/homebrew.yml
      tags: [homebrew]
    - include: tasks/zsh.yml
      tags: [zsh]
    - include: tasks/dotfiles.yml
      tags: [dotfiles]
    - include: tasks/rvm.yml
      tags: [rvm]
